### ISSUE TITLE
رویدادهای نسبی

### ISSUE THREAD

**Issue by okian** [fzerorubigd/cal-events#8]
بعضی رویدادها نسبی هستند مثلا روز قدس (آخرین جمعه ماه رمضان) یا چهارشنبه سوری (غروبِ سه‌شنبه، شبِ پیش از آخرین چهارشنبهٔ ماه اسفند) که البته من به غیر از این دو در تقویم‌های این منطقه مورد دیگری سراغ ندارم ولی در باقی تقویم‌ها مورد مشابه زیاد هست مثل:
 Thanks giving, Black friday 
سوال این هست که این موارد چطور باید هندل بشه؟

**Comment by fzerorubigd** [comment]
بله، قطعا باید یه روش برای این در نظر بگیریم که احتمالا به تعریف یک نو مشخص رویداد ختم میشه. ولی فعلا ایده‌آی ندارم.

**Comment by fzerorubigd** [comment]
این ایشو اهمیت بالایی پیدا کرده الان و بهتره هر چه زودتر یه فکری براش بشه .

**Comment by hramezani** [comment]
میتونیم واسه هر ماه یه کلید
relative_events
داشته باشیم کنار ایونت ها و این رویداد ها رو اونجا بزنیم
احتمالا این ایونت ها دیگه کلید روز نخواهند داشت
و تو توضیحات میشه گفت که اولین دوشنبه ماه یا آخرین چهارشنبه

**Comment by okian** [comment]
@hramezani 
باید قابل محاسبه باشه

**Comment by fzerorubigd** [comment]
مساله اینه که توضیحات صرفا یه چیزیه که قرار نیست کسی روش پردازشی انجام بده. 

این حالتها رو من یادم میاد : دوشنبه منظور یه روز عمومی هفتست

هفته اول، دوم و سوم و آخر 
اولین دوشنبه ، دومین دوشنبه، سومین دوشنبه - آخرین دوشنبه ماه 
اولین دوشنبه سال - آخرین دوشنبه سال 
دهه اول محرم

**Comment by fzerorubigd** [comment]
حالت دیگه ای کسی به ذهنش نمیرسه؟ همش همیناست؟

**Comment by hramezani** [comment]
من حالت دیگه ای  رو یادم نمیاد

**Comment by sbabashahi** [comment]
حالت دیگه میشه چند سال یکبار
20 October (every five years, beginning in 2010)
World Statistics Day

**Comment by okian** [comment]
من فعلا دو راه به نظرم میرسه:
۱- تا یک تاریخی مثلا ۱۰۰ سال آینده رو اطلاعات رو جمع کنیم و داخل یک آرایه قرار بدیم. که این روش رو اصلا دوست ندارم
۲- یک سینتکس طراحی کنیم برای محاسبه این موارد٬ چیزی شبیه 
crontab

**Comment by fzerorubigd** [comment]
کرون تب زیادی «لینوکسی» پسنده. شاید بعضیا بگن گیکی. 
من پیشنهادم اینه یه مدل تعریف شه این شکلی :

```yaml

# last monday in year
condition:
  - type: weekday
    parameter: Monday  
    span: year
    pattern: last
--- 

# first week of the month
condition:
  - type: week
    span: month
    pattern: first

----
# last friday of the month
condition:
  - type: weekday
    parameter: Friday
    span: month
    pattern: last
----
# every 4 years
  - type: year
    parameter: 4

# دهه اول ماه
  - type : decade
    span: month 
    pattern: 1 # 1, 2, last 
```
اگه اسپن ماه باشه، باید کلید 
month 
رو هم داشته باشه

**Comment by amin3mej** [comment]
> کرون تب زیادی «لینوکسی» پسنده. شاید بعضیا بگن گیکی.
> من پیشنهادم اینه یه مدل تعریف شه این شکلی :
> 
> ```yaml
> # last monday in year
> condition:
>   - type: weekday
>     parameter: Monday  
>     span: year
>     pattern: last
> --- 
> 
> # first week of the month
> condition:
>   - type: week
>     span: month
>     pattern: first
> 
> ----
> # last friday of the month
> condition:
>   - type: weekday
>     parameter: Friday
>     span: month
>     pattern: last
> ----
> # every 4 years
>   - type: year
>     parameter: 4
> 
> # دهه اول ماه
>   - type : decade
>     span: month 
>     pattern: 1 # 1, 2, last 
> ```
> 
> اگه اسپن ماه باشه، باید کلید
> month
> رو هم داشته باشه

بنظرم دوتا ویژگی می‌تونه بیشتر داشته باشه.
۱. اون type رو بشکنیم و تبدیلش کنیم به دوتا فیلد،‌ شاید بهتر باشه. مثلا یه type رو بگیم که چند روز ممتده یا فقط یه دونه آخر ماه است یا هر دوشنبه است. و یه فیلد هم بگید که روی کدوم فیلد قصد داریم شرط اعمال بشه؛ روز یا ماه هفته. 

۲. بشه and گذاشت بین شروط. اینجوری میشه در حالات خاصی که ممکنه در آینده پیش بیاد، از همین ساختار استفاده کرد.

**Comment by fzerorubigd** [comment]
and 
رو کاملا مخالفم. همین الانشم برای کوئری این روش بد هست به اندازه کافی. یعنی نمیدونم چطور میشه رو همون ساختاری که من پیشنهاد دادم گشت :/ آینده نگری خوبه، ولی  این همین الانشم بده به نظرم. 

بیشتر باید طرف مقابل رو ببینی، اینکه چجوری میشه رسید به اینکه امروز این رویداد هست یا نه.

**Comment by fzerorubigd** [comment]
پیشنهاد خودمم مسخرست. فرض کن امروز روز ایکس از ماه ایگرگه. چجوری میشه فهمید رویداد اولی الان هست یا نه. معضل اینه که این اطلاعات باید طوری باشه که پیدا کردنش ساده باشه نه ثبت کردنش.

**Comment by okian** [comment]
در مثلا
```yaml
# every 4 years
  - type: year
    parameter: 4
```
شامل ۲۰۱۹ میشه یا نه؟ 😁
باید مبدا داشته باشه.
در مورد دهه هم همینطور٬ دهه فجر از ۱۲ام شروع میشه.
خوبیش اینه که تعدادشون زیاد نیست و میشه برای بیشتر دیتا‌بیس‌ها فانکشن نوشت که تاریخ بگیره و با رکوردها چک کنه بدون اینکه فشاری بیاد
